WebAppSiyakha/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WebAppSiyakha.Models
{

    public class Payment
    {
        [Key]
        [Display(Name = "ID")]
        public int payment_ID { get; set; }
        [Display(Name = "Customer Name")]
        [Required]
        public string custId { get; set; }
        [Required]
        [Display(Name = "Date")]
        public DateTime Date { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Amount")]
        public double AmountPaid { get; set; }
        [Required]
        [Display(Name = "Description")]
        public string PaymentFor { get; set; }
        [Required]
        [Display(Name = "Payment Method")]
        public string PaymentMethod { get; set; }

        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

WebAppSiyakha/Controllers/PDFController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Text;
using System.Net.Mail;
using WebAppSiyakha.Models;
using WebAppSiyakha.Models.Business;

namespace WebAppSiyakha.Controllers
{
    public class PDFController : Controller
    {
        private ApplicationDbContext applicationDb = new ApplicationDbContext();
        [Authorize]
        public FileResult CreatePdf()
        {
            var order = applicationDb.Orders.Where(l => l.Email == User.Identity.Name).FirstOrDefault();
            MemoryStream workStream = new MemoryStream();
            StringBuilder status = new StringBuilder("");
            DateTime dTime = DateTime.Now;
            //file name to be created 
            string strPDFFileName = string.Format("OderDetails.pdf");
            iTextSharp.text.Document doc = new iTextSharp.text.Document();
            doc.SetMargins(0f, 0f, 0f, 0f);
            //Create PDF Table with 5 columns
            PdfPTable tableLayout = new PdfPTable(6);
            doc.SetMargins(0f, 0f, 0f, 0f);

            string strAttachment = Server.MapPath("~/Downloads/" + strPDFFileName);
            PdfWriter.GetInstance(doc, workStream).CloseStream = false;
            doc.Open();
          //  string imagepath = Server.MapPath(Url.Content("~/Content/Images/logo_type.jpg"));
            doc.Add(new Paragraph(""));

            //Image gif = Image.GetInstance(imagepath);

            //doc.Add(gif);
            Chunk c1 = new Chunk("Order Num : " + order.OrderNo);
            DateTime dt = DateTime.Now;
            Chunk chunk = new Chunk("                                          Date Ordered : " + dt.ToString(), FontFactory.GetFont("dax-black"));
            doc.Add(new Paragraph("Contact Details"));
            chunk.SetUnderline(0.5f, -1.5f);

            doc.Add(c1);
            doc.Add(chunk);

            doc.Add(Add_Content_To_PDF(tableLayout, order.OrderNo,order));

            // Closing the document
            doc.Close();

            byte[] byteInfo = workStream.ToArray();
            workStream.Write(byteInfo, 0, byteInfo.Length);
            workStream.Position = 0;
            MemoryStream workStream2 = new MemoryStream();
            workStream2 = workStream;
            MailMessage msg = new MailMessage();


            //string fileName = Path.GetFileName(fileUploader.FileName);

            msg.Attachments.Add(new Attachment(workStream, strPDFFileName));

            //}
            msg.From = new MailAddress("abantwanaweb@gmail.com");
            msg.To.Add(new MailAddress(order.Email));
            msg.Subject = "New Order";
            msg.Body = "Please Find Attached Order details";
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", Convert.ToInt32(587));
            System.Net.NetworkCredential credentials = new System.Net.NetworkCredential("abantwanaweb@gmail.com", "#Account{2020}");
            smtpClient.Credentials = credentials;
            smtpClient.EnableSsl = true;
            smtpClient.Send(msg);

            return File(workStream2, "application/pdf", strPDFFileName);

        }



        protected PdfPTable Add_Content_To_PDF(PdfPTable tableLayout, int id,Order order)
        {

            float[] headers = { 35, 35, 35, 35, 35, 35 };  //Header Widths
            tableLayout.SetWidths(headers);        //Set the pdf headers
            tableLayout.WidthPercentage = 100;       //Set the PDF File witdh percentage
            tableLayout.HeaderRows = 1;
            //Chunk c1 = new Chunk("A chunk represents an isolated string. ");

            tableLayout.AddCell(new PdfPCell(new Phrase("Order Details", new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0)))) { Colspan = 12, Border = 0, PaddingBottom = 5, HorizontalAlignment = Element.ALIGN_CENTER });


            ////Add header
            AddCellToHeader(tableLayout, "Item Code");
            AddCellToHeader(tableLayout, "Item Name");
            AddCellToHeader(tableLayout, "Item description");
            AddCellToHeader(tableLayout, "Quantity");
            AddCellToHeader(tableLayout, "Unit Price");
            AddCellToHeader(tableLayout, "Subtotal");

            ////Add body

            //Employee em = new Employee();
            //Student Studentz = new Student();
            // List<Employee> el = new List<Employee>();
            Order_Business orderB = new Order_Business();

            foreach (var item in orderB.cust_Order_items(id))
            {

                //decimal subtotal = item.Quantity * item.Price;
                AddCellToBody(tableLayout, item.ItemCode.ToString());
                AddCellToBody(tableLayout, item.Item.Name);
                AddCellToBody(tableLayout, item.Item.Description);
                AddCellToBody(tableLayout, item.quantity.ToString());
                AddCellToBody(tableLayout, item.price.ToString());
                var subtotal = item.price * item.quantity;
                AddCellToBody(tableLayout, subtotal.ToString());


            }


            tableLayout.AddCell(new PdfPCell(new Phrase("Total : " + order.TotalPrice, new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0)))) { Colspan = 12, Border = 0, PaddingBottom = 5, HorizontalAlignment = Element.ALIGN_CENTER });

            return tableLayout;
        }

        // Method to add single cell to the Header
        private static void AddCellToHeader(PdfPTable tableLayout, string cellText)
        {

            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.YELLOW))) { HorizontalAlignment = Element.ALIGN_LEFT, Padding = 5, BackgroundColor = new iTextSharp.text.BaseColor(128, 0, 0) });
        }

        // Method to add single cell to the body
        private static void AddCellToBody(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.BLACK))) { HorizontalAlignment = Element.ALIGN_LEFT, Padding = 5, BackgroundColor = new iTextSharp.text.BaseColor(255, 255, 255) });
        }
    }
}

WebAppSiyakha/Controllers/ShoppingController.cs
using WebAppSiyakha.Models.Business;
using WebAppSiyakha.Models;
using Microsoft.AspNet.Identity;
using WebAppSiyakha.Models.HelperToast;
using WebAppSiyakha.Controllers.Extensions;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SiyakhaFrontV1.Controllers
{
    public class ShoppingController : Controller
    {
        private CartBusiness cart_Service = new CartBusiness();
        private ItemBusiness item_Service = new ItemBusiness();
        private Order_Business Order_Business = new Order_Business();
        private DepartmentBusiness department_Service;
        public ActionResult Index(int? id)
        {
            var items_results = new List<Item>();
            try
            {
                if (id != null)
                {
                    if (id == 0)
                    {
                        items_results = item_Service.GetItems().ToList();
                        ViewBag.Department = "All Categories";
                    }
                    else
                    {
                        int notnull = Convert.ToInt16(id);
                        items_results = item_Service.GetItems().Where(x => x.Department.Department_ID == (int)id).ToList();
                        ViewBag.Department = department_Service.GetDepartment(notnull).Department_Name;
                    }
                }
                else
                {
                    items_results = item_Service.GetItems().ToList();
                    ViewBag.Department = "All Categories";
                }
            }
            catch (Exception) { }
            return View(items_results);
        }
        public ActionResult increaseItemQuantity(string id)
        {
            var item = cart_Service.GetCartItems().FirstOrDefault(x => x.Id == id);
            if (item != null)
            {
                cart_Service.increaseItemQuantity(id: id);
                this.AddToastMessage("Success!", item.Item.Name + " quantity has been increased", ToastType.Success);
                return RedirectToAction("ShoppingCart");
            }
            else
                this.AddToastMessage("Item Error!", "An unexpected error has occured", ToastType.Error);
            return RedirectToAction("ShoppingCart");
        }
        public ActionResult decreaseItemQuantity(string id)
        {
            var item = cart_Service.GetCartItems().FirstOrDefault(x => x.Id == id);
            if (item != null)
            {
                cart_Service.decreaseItemQuantity(id: id);
                this.AddToastMessage("Success!", item.Item.Name + " quantity has been decreased", ToastType.Success);
                return RedirectToAction("ShoppingCart");
            }
            else
                this.AddToastMessage("Item Error!", " An unexpected error has occured", ToastType.Error);
            return RedirectToAction("ShoppingCart");
        }
        public ActionResult add_to_cart(int id)
        {
            var UserName = User.Identity.GetUserName();
            int qty = 1;
            var item = item_Service.GetItem(id);
            CartItem ct = new CartItem();
            if (item != null)
            {
                cart_Service.UpdateQuantity(id, qty);
                //cart_Service.UpdateCart(item.ItemCode,item.Cart_Items.);
                cart_Service.AddItemToCart(id, UserName);
                this.AddToastMessage("Success!", item.Name + " quantity has been added", ToastType.Success);
                return RedirectToAction("Index");
            }
         
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult remove_from_cart(string id)
        {
            var item = cart_Service.GetCartItems().FirstOrDefault(x => x.Id == id);
            if (item != null)
            {
                cart_Service.RemoveItemFromCart(id: id);
                this.AddToastMessage("Success!", item.Item.Name + "  has been removed", ToastType.Success);
                return RedirectToAction("ShoppingCart");
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult ShoppingCart()
        {
            ViewBag.Total = cart_Service.GetCartTotal(cart_Service.GetCartID());
            ViewBag.TotalQTY = cart_Service.GetCartItems().FindAll(x => x.cartId == cart_Service.GetCartID()).Sum(q => q.quantity);
            return View(cart_Service.GetCartItems().FindAll(x => x.cartId == cart_Service.GetCartID()));
        }
        [HttpPost]
        public ActionResult ShoppingCart(List<CartItem> items)
        {
            foreach (var i in items)
            {
                cart_Service.UpdateCart(i.Id, i.quantity);
            }
            return RedirectToAction("ShoppingCart");
        } 
        public ActionResult EmptyCart(List<CartItem> items)
        {
            cart_Service.EmptyCart();
            
            return RedirectToAction("ShoppingCart");
        }
        public ActionResult countCartItems()
        {
            var username = User.Identity.GetUserName();
            int qty = cart_Service.GetCartItems().Sum(x => x.quantity);
            return Content(qty.ToString());
        }
        public ActionResult Checkout()
        {
            if (cart_Service.GetCartItems().Count == 0)
            {
                ViewBag.Err = "Opps... you should have atleast one cart item, please shop a few items";
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("HowToGetMyOrder");
        }
        [Authorize]
        public ActionResult HowToGetMyOrder()
        {
            return View();
        }
        [HttpPost]
        public ActionResult HowToGetMyOrder(FormCollection formCollection)
        {
           /* Session["street_number"]*/ string streetNume = formCollection["StreetNumber"];
            /*Session["street_name"] */ string streetName = formCollection["street_name"];
            Session["City"] = formCollection["City"];
            Session["State"] = formCollection["State"];
            Session["ZipCode"] = formCollection["ZipCode"];
            Session["Country"] = formCollection["Country"];
            return RedirectToAction("PlaceOrder", new { id = "deliver" });
        }
        [Authorize]
        public ActionResult PlaceOrder(string id)
        {
            /* Find the details of the customer placing the order*/
            ApplicationDbContext dataContext = new ApplicationDbContext();
            var user = dataContext.Users.ToList().Find(x=>x.Email == HttpContext.User.Identity.Name);
            var customer = new ApplicationUser(); 
            /* Place the order */
            dataContext.Orders.Add(new Order()
            {
                Email = user.Email,
                dateCraeted = DateTime.Now,
                shipped = false,
                status = "Awaiting Payment",
                TotalPrice = cart_Service.GetCartTotal(cart_Service.GetCartID())
            });

            dataContext.SaveChanges();
            var order = dataContext.Orders.ToList()
                .FindAll(x => x.Email == user.Email)
                .OrderByDescending(x => x.dateCraeted)
                .FirstOrDefault();
            /* If the customer requests delivery, save order address */
            if (id == "deliver")
            {
                dataContext.SaveChanges();
                try
                {
                    dataContext.OrderAddresses.Add(new OrderAddress()
                    {
                        OrderNo = order.OrderNo,
                        street = Session["street_name"].ToString(),
                        city = Session["City"].ToString(),
                        zipcode = Session["ZipCode"].ToString()
                        
                    });
                }
                catch (Exception x)
                {
                   var m = x.Message;
                }
            }
            /* Migrate cart items to map as order items */
            //   order_Service.AddOrderItems(order, cart_Service.GetCartItems());
            var items = cart_Service.GetCartItems();

            foreach (var item in items)
            {
                var x = new OrderItem()
                {
                    Order_ID = order.OrderNo,
                    ItemCode = item.ItemdId,
                    quantity = item.quantity,
                    price = item.price
                   
                };


                //   ob.updateStock_bot(x.item_id, x.quantity);
                // db.OrderItems.Add(x);
                // db.SaveChanges();
                dataContext.OrderItems.Add(x);
            }
            dataContext.SaveChanges();
            /* Empty the cart items */
            cart_Service.EmptyCart();
            /* Update Order Tracking Report */
            dataContext.Order_Trackings.Add(new OrderTracking()
            {
                orderNo = order.OrderNo,
                date = DateTime.Now,
                status = "Awaiting Payment",
                Recipient = ""
            });
            dataContext.SaveChanges();
            //Redirect to payment
             return RedirectToAction("Payment", new { id = order.OrderNo });
           // return RedirectToAction("Payment",new { id = order.OrderNo });
        }
        public ActionResult Payment(int id)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            //var order = _orderRepository.GetById(id); //db.Orders.Find(id);
            //ViewBag.Order = order;

            //ViewBag.Account = context.Users.Find(order.Email);   //db.Customers.Find(order.custId);
            //ViewBag.name = order.FirstName;
            //ViewBag.lname = order.LastName;

WebAppSiyakha/Views/Shopping/HowToGetMyOrder.cshtml
@{
    ViewBag.Title = "How would you like to receive your order?";
}
<h2 class="title text-center">@ViewBag.Title</h2>
<form method="post">
    <div class="row">
        <div class="board">
            <!-- <h2>Welcome to IGHALO!<sup>™</sup></h2>-->
            <div class="board-inner">
                <ul class="nav nav-tabs" id="myTab">
                    <li class="active" style="text-align:center">
                        <a href="#home" data-toggle="tab" title="Collect at warehouse">
                            <span class="round-tabs">
                                <i class="fa fa-home"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#profile" data-toggle="tab" title="Standard Delivery">
                            <span class="round-tabs">
                                <i class="fa fa-truck"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade in active" id="home">
                    <h4 class="head text-center">Collect your order at our warehouse.</h4>
                    <h4> <i class="fa fa-map-marker"></i>  123 Sept St, Durban, 4001 </h4>
                    <h4> <i class="fa fa-clock-o"></i>  Monday - Friday</h4>
                    <h4> <i class="fa fa-clock-o"></i>  8:30 am - 17:00 pm working hours</h4>
                    <a href="@Url.Action("PlaceOrder","Shopping", new {id = "collect" })" class="btn btn-default"> Continue</a>
                </div>
                <div class="tab-pane fade" id="profile">
                    <h3 class="head text-center">Deliver the order to my address</h3>
                    <div class="input_field">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-map-marker"></i>
                            </div>
                            @*<textarea type="text" class="form-control" id="Physical_Address" ng-model="PropertyModel.Physical_Address" required ng-minlength="3" ng-maxlength="255" style="min-height:100px; resize:none" placeholder="Physical Address"></textarea>*@
                            <div id="locationField">
                                <input id="autocomplete" name="autocomplete" placeholder="Enter your address here" required class="form-control" onFocus="geolocate()" type="text" style="min-width:360px" />
                            </div>
                            <br />
                            <table id="address">
                                <tr>
                                    <td style="color:black;width:70px"><i>Street</i></td>
                                    <td style="min-width:460px" colspan="2">
                                        <input id="street_number" name="street_number" class="field form-control disabled" disabled required="required" style="max-width:60px" />
                                        <input class="field form-control disabled" id="route" disabled name="street_name" required="required" style="max-width:220px" />
                                    </td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>City</i></td>
                                    <td class="wideField" colspan="3">
                                        <input class="field  form-control disabled" id="locality" disabled name="City" required="required" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>State</i></td>
                                    <td style="min-width:460px" colspan="2">
                                        <input class="field form-control disabled" id="administrative_area_level_1" name="State" disabled style="max-width:80px" />
                                        &nbsp;&nbsp;&nbsp;
                                        <i>Zip Code</i>
                                        &nbsp;&nbsp;&nbsp;
                                        <input class="field form-control disabled" id="postal_code" name="ZipCode" disabled required="required" style="max-width:102px" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>Country</i></td>
                                    <td colspan="3">
                                        <input class="field  form-control disabled" disabled name="Country" id="country" />
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
                                        <input type="submit" value="Continue" class="btn btn-default" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    $(function () {
        $('a[title]').tooltip();
    });
</script>
<script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvBbwz438d_K-EN-t3YlT6ZAzBT0TQmiU&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            @*/** @type {!HTMLInputElement} */*@(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
            document.getElementById(component).value = '';
            document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvBbwz438d_K-EN-t3YlT6ZAzBT0TQmiU&libraries=places&callback=initAutocomplete"
        async defer></script>
<script>
    $(function () {
        var input = document.getElementById("autocomplete");
        var autocomplete = new google.maps.places.Autocomplete(input);

        $('#my-modal').modal('show');

    });

</script>

WebAppSiyakha/Views/Shopping/Payment.cshtml
@model WebAppSiyakha.Models.OrderDetailConFirm


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Payment";


}

<h2 class="title text-center">Order Details </h2>

<div class="row">
    <div class="col-md-4">
        <b>Account Details</b>
        @*@{ Data.ApplicationUser Account = (Data.ApplicationUser)ViewBag.Account; }*@

        <table class="table">
            <tr>
                <td>Name</td>
                <td>@Model.order.FirstName   @Model.order.LastName</td>
            </tr>
            @*<tr>
                <td>Cell Number</td>
                <td>@Model.order.customer.PhoneNumber</td>
            </tr>*@
            <tr>
                <td>Email</td>
                <td>@Model.order.Email</td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">

        <b>Order Details</b>
        @*@{ Data.ShoppingCartM.Order order = (Data.ShoppingCartM.Order)ViewBag.Order; }*@

        <table class="table">
            <tr>
                <td>Order No.</td>
                <td>@Model.order.OrderNo</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>@Model.order.status</td>
            </tr>

        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4">

        <b>Shipping Details</b>
        @{ WebAppSiyakha.Models.OrderAddress address = (WebAppSiyakha.Models.OrderAddress)ViewBag.Address; }
        @if (address != null)
        {
            <table class="table">
                <tr>
                    <td>Street</td>
                    <td>@Model.address.street</td>
                </tr>
                <tr>
                    <td>City/Town</td>
                    <td>@Model.address.city</td>
                </tr>
                <tr>
                    <td>Zipcode</td>
                    <td>@Model.address.zipcode</td>
                </tr>
            </table>
        }
        else
        {
            <hr />
            <p>
                <b> Collect your order at our Company.</b>
                <br />
                <i class="fa fa-map-marker"></i>  21 May St, Durban, 4001
                <br />
                <i class="fa fa-clock-o"></i>  8:30 am - 17:00 working hours
                <br />
            </p>
        }

    </div>
    <div class="col-md-8">

        <b>Items in this Order</b>
        <table class="table">
            <tr>
                <th>
                    Picture
                </th>
                <th>
                    Item
                </th>
                <th>
                    Qty
                </th>
                <th>
                    Price
                </th>
            </tr>

            @foreach (var item in (List<WebAppSiyakha.Models.OrderItem>)ViewBag.Items)
            {
                <tr>
                    <td>
                        @if (item.Item.Picture != null)
                        {
                            var base64 = Convert.ToBase64String(inArray: item.Item.Picture);
                            var imgSrc = string.Format(format: "data:image/gif;base64,{0}", arg0: base64);
                            <img src=@imgSrc width="60" height="70" />
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantity)
                    </td>
                    <td>
                        R @Html.DisplayFor(modelItem => item.price)
                    </td>
             </tr>
            }

            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <b>R @Model.order.TotalPrice</b>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    @*<a href="@Url.Action("OrderThankYou", "Home")" class="btn btn-success"><i class="fa fa-lock"></i> Done</a>*@
                   @* <a href="@Url.Action("Secure_Payment", "Shopping", new { id = Model.order.OrderNo})" class="btn btn-success"><i class="fa fa-lock"></i> Secure Payment</a>*@
                    <a href="@Url.Action("CreatePdf", "PDF")" class="btn btn-success"><i class="fa fa-lock"></i> Send Details</a>

                </td>
            </tr>
        </table>

    </div>


</div>