WebAppSiyakha/Models/HelperToast/Toastr.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WebAppSiyakha.Models.HelperToast
{
    [Serializable]
    public class Toastr
    {
        public bool ShowNewestOnTop { get; set; }
        public bool ShowCloseButton { get; set; }
        public bool IsSticky { get; set; }
        public bool ProgressBar { get; set; }
        public List<ToastMessage> ToastMessages { get; set; }

        public ToastMessage AddToastMessage(string title, string message, ToastType toastType)
        {
            var toast = new ToastMessage()
            {
                Title = title,
                Message = message,
                ToastType = toastType,


            };
            ToastMessages.Add(toast);
            return toast;
        }

        public Toastr()
        {
            ToastMessages = new List<ToastMessage>();
            ShowNewestOnTop = true;
            ShowCloseButton = false;
            IsSticky = true;
            ProgressBar = true;
        }

    }
}

WebAppSiyakha/Controllers/ItemsController.cs
using WebAppSiyakha.Models.Business;
using WebAppSiyakha.Models;
using WebAppSiyakha.Controllers.Extensions;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace WebAppSiyakha.Controllers
{
    public class ItemsController : Controller
    {
        private ItemBusiness item = new ItemBusiness();

        DepartmentBusiness category_Service = new DepartmentBusiness();
        ApplicationDbContext appDb = new ApplicationDbContext();
       
        public ActionResult Index()
        {
            return View(item.GetItems());
        }
        public ActionResult Details(int id)
        {
            
            if (item.GetItem(id) != null)
                return View(item.GetItem(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult Create()
        {
            ViewBag.Department_ID = new SelectList(category_Service.GetDepartments(), "Department_ID", "Department_Name");
            ViewBag.SupplierId = new SelectList(appDb.Suppliers.ToList(), "SupplierId", "SupplierName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "img_upload")] Item model)
        {
            ViewBag.Department_ID = new SelectList(category_Service.GetDepartments(), "Department_ID", "Department_Name");
            ViewBag.SupplierId = new SelectList(appDb.Suppliers.ToList(), "SupplierId", "SupplierName");
            if (ModelState.IsValid)
            {
                byte[] Pic = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["img_upload"];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        Pic = binary.ReadBytes(poImgFile.ContentLength);
                    }
                }
                model.Picture = Pic;
                item.AddItem(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            if (item.GetItem(id) != null)
            {
                ViewBag.Department_ID = new SelectList(category_Service.GetDepartments(), "Department_ID", "Department_Name", item.GetItem(id).Department_ID);
                return View(item.GetItem(id));
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Item model, HttpPostedFileBase img_upload)
        {
            if (img_upload != null)
            {
                string ext = Path.GetExtension(img_upload.FileName);
                if (ext != ".png" && ext != ".PNG" && ext != ".jpg" && ext != ".JPG" && ext != ".jpeg" && ext != ".JPEG")
                {
                }
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Content/Images/"), Guid.NewGuid().ToString() + Path.GetExtension(img_upload.FileName));
                    img_upload.SaveAs(path);
                    model.ImgPath = path.Substring(path.LastIndexOf("\\") + 1);
                }
                catch (Exception e)
                {
                    var err = e.Message;
                }
            }
            if (ModelState.IsValid)
            {
                item.UpdateItem(model);
                return RedirectToAction("Index");
            }
            ViewBag.Department_ID = new SelectList(category_Service.GetDepartments(), "Department_ID", "Department_Name",model.Department_ID);
            return View(model);
        }
        public JsonResult Delete(int id)
        {
            try
            {
                var update = item.RemoveItem(item.GetItem(id));
                this.AddToastMessage("Success", "Department succesfully deleted", WebAppSiyakha.Models.HelperToast.ToastType.Success);
            }
            catch
            {
            }
            return Json(new object[] { new object() }, JsonRequestBehavior.AllowGet);
        }

        //Statistics below

        public ActionResult ItemStats()
        {
            return View();
        }
        public ActionResult ProfitChart()
        {
            ApplicationDbContext Mealcontext2 = new ApplicationDbContext();
            ArrayList xValue = new ArrayList();
            ArrayList yValue = new ArrayList();

            var profits = (from p in Mealcontext2.Items select p);
            profits.ToList().ForEach(pr => xValue.Add(pr.Name));
            profits.ToList().ForEach(pr => yValue.Add(pr.calculateCostDifference()));

            new Chart(width: 700, height: 450, theme: ChartTheme.Blue)
                .AddTitle("Profit Made Per Meal")
                .AddSeries("Default", chartType: "Column", xValue: xValue, yValues: yValue)
                .SetXAxis(title: "Meal Name")
                .SetYAxis(title: "Profit in Rands")
                .Write("jpeg");

            return null;

        }
        public ActionResult SalePriceChart()
        {
            ApplicationDbContext Mealcontext2 = new ApplicationDbContext();
            ArrayList xValue = new ArrayList();
            ArrayList yValue = new ArrayList();

            var profits = (from p in Mealcontext2.Items select p);
            profits.ToList().ForEach(pr => xValue.Add(pr.Name));
            profits.ToList().ForEach(pr => yValue.Add(pr.Price));

            new Chart(width: 700, height: 450, theme: ChartTheme.Blue)
                .AddTitle("Sale Price Per Meal")
                .AddSeries("Default", chartType: "Column", xValue: xValue, yValues: yValue)
                .SetXAxis(title: "Meal Name")
                .SetYAxis(title: "Sale Price in Rands")
                .Write("jpeg");

            return null;

        }
    }
}

WebAppSiyakha/Views/Shared/_AdminLayout.cshtml
@*<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>*@

@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

    <!-- Bootstrap core CSS -->
    @*<link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Content/dashboard.css" rel="stylesheet" />
    @*<link href="dashboard.css" rel="stylesheet">*@
</head>

<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">  Siyakha</a>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="SearchString">
        @*<ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                @using Microsoft.AspNet.Identity
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Sign out</a></li>
                        </ul>
                    }
                }
                <a class="nav-link" href="#">Sign out</a>
            </li>
        </ul>*@
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="@(Url.Action("WithLayout","Admin"))">
                                <span data-feather="home"></span>
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@(Url.Action("Index","Departments"))">
                                <span data-feather="file"></span>
                                Departments
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file"></span>
                                Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="shopping-cart"></span>
                                Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="users"></span>
                                Customers
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Reports
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="layers"></span>
                                Integrations
                            </a>
                        </li>
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Year-end sale
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                    <h1 class="h2">@ViewBag.Title</h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group mr-2">
                            <button class="btn btn-sm btn-outline-secondary">Share</button>
                            <button class="btn btn-sm btn-outline-secondary">Export</button>
                        </div>
                        <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                            <span data-feather="calendar"></span>
                            This week
                        </button>
                    </div>

                </div>
                @RenderBody()

            </main>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    @RenderSection("scripts", required: false)
    @{ Html.RenderPartial("_Toastr"); }

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
</body>
</html>

WebAppSiyakha/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/toastr")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .navbar-inverse {
            background-color: #000000 !important;
        }
    </style>
</head>
@{ var department_Service = new WebAppSiyakha.Models.Business.DepartmentBusiness();

    var cart_Service = new WebAppSiyakha.Models.Business.CartBusiness();
    double total = 0; }
<body>
    <div class="navbar navbar-inverse navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("No Name", "Index", "Shopping", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Shopping")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("User Manual", "Index", "Manuals")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Departments")</li>
                    <li>@Html.ActionLink("Manage Products", "Index", "Items")</li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle active" id="navbardropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-shopping-cart" style="font-size:24px" aria-hidden="true"></i>  (@Html.Action(actionName: "countCartItems", controllerName: "Shopping"))<span class="caret"></span></a>
                        <ul class="dropdown-menu mega">
                            <ul class="sub-menu">
                                <table class="table">
                                    <tr class="card-header bg-dark text-light">
                                        <th>Item</th>
                                        <th>
                                        </th>
                                        <th style="text-align:center">
                                            Quantity
                                        </th>
                                        <th>
                                            Price
                                        </th>
                                        <th style="text-align:center">
                                            Sub-Total
                                        </th>
                                    </tr>
                                    @if (cart_Service.GetCartItems().Count() == 0)
                                    {
                                        <tr>
                                            <th colspan="5" style="text-align:center">Your cart is empty</th>
                                        </tr>
                                    }
                                    @foreach (var item in cart_Service.GetCartItems().OrderBy(x => x.Item.Name))
                                    {
                                        <tr>
                                            <td>
                                                @if (item.Item.Picture != null)
                                                {
                                                    var base64 = Convert.ToBase64String(inArray: item.Item.Picture);
                                                    var imgSrc = string.Format(format: "data:image/gif;base64,{0}", arg0: base64);
                                                    <img src=@imgSrc width="30" height="30" />
                                                }
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Details","Items", new { id=item.Item.ItemCode })">@item.Item.Name</a>
                                            </td>
                                            <td style="text-align:center">
                                                @item.quantity
                                            </td>
                                            <td>
                                                @item.Item.Price.ToString("C")
                                            </td>
                                            <td style="text-align:center">
                                                @{ var subtotal = item.quantity * item.Item.Price;
                                                    total += subtotal; }
                                                @subtotal.ToString("C")
                                            </td>
                                        </tr>
                                    }
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td style="text-align:center">
                                            Total
                                        </td>
                                        <th style="text-align:center">
                                            @total.ToString("C")
                                        </th>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>
                                            <a class="btn btn-default" href="@Url.Action("Index","Shopping")">
                                                <i class="fa fa-list"></i> Shop More
                                            </a>
                                        </td>
                                        <td>
                                            <a class="btn btn-default" href="@Url.Action("ShoppingCart", "Shopping")">
                                                <i class="fa fa-shopping-cart"></i> View Cart
                                            </a>
                                        </td>
                                        <td>
                                            @if (cart_Service.GetCartItems().Count() == 0)
                                            {
                                                <a class="btn btn-default disabled" href="@Url.Action("Checkout","Shopping")">
                                                    <i class="fa fa-lock"></i> Checkout
                                                </a> }
                                            else
                                            {
                                                <a class="btn btn-default" href="@Url.Action("Checkout","Shopping")">
                                                    <i class="fa fa-lock"></i> Checkout
                                                </a>}
                                        </td>
                                    </tr>
                                </table>
                            </ul>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div style=" margin-bottom:5%"></div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @{ Html.RenderPartial("_Toastr"); }
</body>
</html>

WebAppSiyakha/Views/Shared/_Toastr.cshtml
@using WebAppSiyakha.Models.HelperToast
@if (TempData.ContainsKey("Toastr"))
{
    Toastr toastr = TempData["Toastr"] as Toastr;
    @ToastrBuilder.ShowToastMessages(toastr);
}